# Generated by Django 3.2.13 on 2022-06-20 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0002_rename_company_name_company_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='company_name',
        ),
    ]
